config/routes.rb
Rails.application.routes.draw do
root "managers#index"


  devise_for :users
  resources :managers

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

has_many :managers

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
        end



end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  def index
    @managers = current_user.managers
  end

  def show
  end

  def new
    @manager = Manager.new
  end

  def create 
    @manager = current_user.managers.new(manager_params)
    if@manager.save
      redirect_to managers_path
    else render :new
    end
  end


  def edit
    render partial: "form"
 
  end

  def update
    if @manager.update(manager_params)
      redirect_to managers_path
    else :edit
    end
  end

  def destroy
    @manager.destroy
    redirect_to managers_path
  end

  private 
  def manager_params
    params.require(:manager).permit(:name, :balance)
  end


  def set_manager
    @manager = current_user.managers.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leauge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/managers/_form.html.erb
<h1><%= @manager.id ? 'Edit league' : 'create league' %></h1>
<hr />
<%= form_for @manager do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/managers/edit.html.erb
<h1>Managers#edit</h1>
<p>Find me in app/views/managers/edit.html.erb</p>

app/views/managers/index.html.erb
<nav>
<div class="nav-wrapper">
  <a href="#" class="brand-logo right">League Manager</a>
  <ul id="nav-mobile" class="left hide-on-med-and-down">
    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    <li><%= link_to "Add a League", new_manager_path %></li>
  </ul>
</div>
</nav>
<h3>Your Leagues</h3>
<ul>
  <% @managers.each do |manager| %>
    <li>
      <h4><%= manager.name %></h4>
      
    <%= link_to "Edit", edit_manager_path(manager) %> |
    <%= link_to "Destroy", manager_path(manager), method: :delete %>
  <% end %>
</ul>

app/views/managers/new.html.erb
<h1>Add League<h1>
<%= form_with(model: @manager, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit

</button>


<% end %>

app/views/managers/show.html.erb
<h1>Managers#show</h1>
<p>Find me in app/views/managers/show.html.erb</p>